POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "seppo2",
    "password": "salasana",
    "name": "Seppo Taalasmaa"
}

###

POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "seppo2",
    "password": "salasana"
}

###

GET http://localhost:3001/api/tournaments

###

GET http://localhost:3001/api/tournaments/5ba0d517bf34a73c92984919

###

POST http://localhost:3001/api/games
Content-Type: application/json

{
    "name": "EA NHL"
}

###

POST http://localhost:3001/api/leagues
Content-Type: application/json

{
    "name": "NHL",
    "apiUrlTeams": "https://statsapi.web.nhl.com/api/v1/teams/",
    "apiUrlPlayers": "https://statsapi.web.nhl.com/api/v1/people/",
    "game": "5ba35dc181a832808d2effab"
}

###

POST http://localhost:3001/api/tournaments
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlcHBvMiIsImlkIjoiNWJhMzQ0MWM3ZDEwNGE3OGVlNTI3ZjY0IiwiaWF0IjoxNTM3NDI2NTc1fQ.c3D-0viViHoMqKqU0MGb6ddbn4Mk-2F9evmG5E48K9g
Content-Type: application/json

{
    "name": "NHL Mayhem 2018",
    "description": "The best game in the world",
    "rounds": 2,
    "toAdvance": 6,
    "league": "5ba35dc181a832808d2effab"
}
